ssh-add -D
ssh-add ~/.ssh/*
AWS_ACCESS_KEY_ID="AKIAJH2NJWY4KY27PGAQ"
AWS_SECRET_ACCESS_KEY="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"
AWS_DEFAULT_REGION="eu-west-1"
ANSIBLE_VAULT_PASSWORD="5r5bAStumawU"
export AWS_ACCESS_KEY_ID
export AWS_SECRET_ACCESS_KEY
export AWS_DEFAULT_REGION
export ANSIBLE_VAULT_PASSWORD

